/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_interviewstudy_jni_MyJniCall */

#ifndef _Included_com_example_interviewstudy_jni_MyJniCall
#define _Included_com_example_interviewstudy_jni_MyJniCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_interviewstudy_jni_MyJniCall
 * Method:    getInt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_interviewstudy_jni_MyJniCall_getInt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_interviewstudy_jni_MyJniCall
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_interviewstudy_jni_MyJniCall_getString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_interviewstudy_jni_MyJniCall
 * Method:    sayHello
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT static jstring JNICALL sayHello
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
